IdentityRoleAuthorization/IdentityRoleAuthorization/Controllers/ProductController.cs
using IdentityRoleAuthorization.Models.Dtos;
using IdentityRoleAuthorization.Service.Services.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IdentityRoleAuthorization.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAllProduct()
        {
            var products = await _productService.GetProductsAsync();
            return View(products);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(ProductRequestDto productRequestDto)
        {
            if (ModelState.IsValid)
            {
                await _productService.AddProductAsync(productRequestDto);
                return RedirectToAction(nameof(GetAllProduct));
            }

            return View(productRequestDto);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ProductRequestDto productRequestDto)
        {
            if (ModelState.IsValid)
            {
                await _productService.UpdateProductAsync(id, productRequestDto);
                return RedirectToAction(nameof(GetAllProduct));
            }

            return View(productRequestDto);
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productService.DeleteProductAsync(id);
            return RedirectToAction(nameof(GetAllProduct));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteAll()
        {
            var allProducts = await _productService.GetProductsAsync();
            return View("DeleteAll", allProducts);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ConfirmDeleteAll()
        {
            await _productService.DeleteAllProductAsync();
            return RedirectToAction(nameof(GetAllProduct));
        }

        [Authorize]
        public async Task<IActionResult> Search(string searchTerm)
        {
            var products = await _productService.SearchProductsAsync(searchTerm);
            return View("Search", products);
        }
    }
}

IdentityRoleAuthorization/IdentityRoleAuthorization/Controllers/UserController.cs
using Ecommerce.Model.Models.Dtos;
using Ecommerce.Service.Services.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }


        public async Task<IActionResult> AllUsers()
        {
            var users = await _userService.GetAllUsers();
            return View(users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ApplicationUserRequestDto userDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.CreateUserAsync(userDto);

                if (result.Succeeded)
                {
                    return RedirectToAction("AllUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(userDto);
        }

        public async Task<IActionResult> Details(string userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);

            if (user == null)
            {
                return RedirectToAction("AllUsers");
            }

            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);

            if (user == null)
            {
                return RedirectToAction("AllUsers");
            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, ApplicationUserResponseDto updatedUserDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.UpdateUserAsync(userId, updatedUserDto);

                if (result.Succeeded)
                {
                    return RedirectToAction("AllUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(updatedUserDto);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(string userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);

            if (user == null)
            {
                return RedirectToAction("AllUsers");
            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string userId)
        {
            try
            {
                await _userService.DeleteUserAsync(userId);
                return RedirectToAction("AllUsers");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Failed to delete the user.");
                return RedirectToAction("AllUsers");
            }
        }

    }
}

IdentityRoleAuthorization/IdentityRoleAuthorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityRoleAuthorization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" href="~/favicon1.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="~/favicon1.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IdentityRoleAuthorization.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">De Royals</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @*  @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="GetAllProduct">Products</a>
                            </li>
                        } *@
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Product" asp-action="GetAllProduct">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="AllUsers">Users</a>
                            </li>
                        }
                    </ul>

                    <form class="d-flex mx-auto" asp-controller="Product" asp-action="Search" method="get" onsubmit="return validateSearchForm()">
                        <input class="form-control me-1" type="search" placeholder="Search products" aria-label="Search" name="searchTerm" id="searchTerm">
                        <button class="btn btn-outline-success custom-search-btn" type="submit">Search</button>
                    </form>

                    <script>
                        function validateSearchForm() {
                            var searchTerm = document.getElementById("searchTerm").value.trim();

                            if (searchTerm.length < 2) {
                                alert("Please enter at least 2 characters for the search.");
                                return false;
                            }

                            if (!searchTerm) {
                                alert("Please enter a search term.");
                                return false;
                            }

                            return true;
                        }
                    </script>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - De Royals Shopping Malls - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>